// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ihweyawbtgehuvvjrqhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlod2V5YXdidGdlaHV2dmpycWh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4NDM0MDAsImV4cCI6MjA5MTQxOTQwMH0.0H0gVSN8_CCdw76Qcld099bEsw0wfX4M284SHTOsLrg";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);